apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cmstate-operator-webhook
  labels: 
    {{- if or .Values.global.labels }}
    {{ toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.webhook.labels }}
    {{ toYaml .Values.webhook.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if or .Values.global.annotations }}
    {{ toYaml .Values.global.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.webhook.annotations }}
    {{ toYaml .Values.webhook.annotations | nindent 4 }}
    {{- end }}
webhooks:
  - name: cmstate-operator-webhook.spices.dev
    admissionReviewVersions: ["v1"]
    sideEffects: None
    namespaceSelector:
        matchExpressions:
            - key: 'cmstate.spices.dev'
              operator: 'NotIn'
              values:
              - 'opt-out'
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace:  {{ .Release.Namespace }}
        path: "/"
    #   caBundle: {{ .Files.Get "templates/webhook-ca-bundle.txt" | b64enc | quote }}
    rules:
    - operations: [ "CREATE", "DELETE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"

