apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cmstate-operator-webhook
webhooks:
  - name: cmstate-operator-webhook.spices.dev
    namespaceSelector:
      matchExpressions:
        - key: runlevel
          operator: NotIn
          values: ["0","1"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace:  {{ include "chart.namespaceName" .}}
        path: "/"
    #   caBundle: {{ .Files.Get "templates/webhook-ca-bundle.txt" | b64enc | quote }}
    rules:
    - operations: [ "CREATE", "DELETE" ]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
